"""
/***************************************************************************
 DownloadSharedFiles
                                 A QGIS plugin
 This plugin provides a processing algorithm to download files hosted on one or
 multiple web repositories.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-10-28
        copyright            : (C) 2021 by Yann Voté
        email                : ygversil@lilo.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yann Voté'
__date__ = '2021-10-28'
__copyright__ = '(C) 2021 by Yann Voté'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'


import traceback

from qgis.core import Qgis, QgsMessageLog


def log_exception(err, level='Warning', message_bar=False, iface=None,
                  duration=5):
    """Output the given exception in QGIS logs using the given level.

    If ``message_bar`` is ``True``, then ``iface`` must reference a valid
    ``QgisInterface`` instance so that the message can be shown in the message
    bar in QGIS interface.
    """
    log_message(str(err), level=level, message_bar=message_bar, iface=iface,
                duration=duration)
    log_message(traceback.format_exc(), level=level)


def log_message(msg, level='Info', message_bar=False, iface=None,
                duration=5):
    """Output the given message in QGIS logs using the given level.

    If ``message_bar`` is ``True``, then ``iface`` must reference a valid
    ``QgisInterface`` instance so that the message can be shown in the message
    bar in QGIS interface.
    """
    level = getattr(Qgis, level)
    QgsMessageLog.logMessage(msg, 'ANA - CEN Ariège', level=level)
    if message_bar:
        assert iface is not None
        iface.messageBar().pushMessage('ANA - CEN Ariège', msg,
                                       level=level, duration=duration)
